"""Tests of PDB/PQR parsing in :mod:`pdb2pqr.psize`."""

import pytest

from pdb2pqr import psize


def fixed_pqr_line(x, y, z, charge=-0.25, radius=1.5, record="ATOM"):
    """Return a fixed-column PQR record with coordinates in columns 31-54."""
    line = (
        f"{record:6s}{1:5d} {'N':4s} {'GLY':3s} {'A':1s}{1:4d}    "
        f"{x:8.3f}{y:8.3f}{z:8.3f}{charge:8.4f}{radius:7.4f}"
    )
    assert line[30:54] == f"{x:8.3f}{y:8.3f}{z:8.3f}"
    return line


def parse(*lines):
    """Parse the lines with :class:`psize.Psize`."""
    size = psize.Psize()
    size.parse_lines([f"{line}\n" for line in lines])
    return size


def assert_extents(size, center, radius):
    """Check that the extents are those of a single atom."""
    assert size.minlen == pytest.approx([c - radius for c in center])
    assert size.maxlen == pytest.approx([c + radius for c in center])


def test_free_format_with_numbers_at_fixed_columns():
    """Whitespace-delimited records are not read at the fixed columns."""
    line = "ATOM 1 N GLY A 1  100.2500  100.2500  100.2500  -0.2500  1.5000"
    # The fixed coordinate columns hold numbers, but not the coordinates.
    assert float(line[30:38]) != 100.25
    size = parse(line)
    assert size.gotatom == 1
    assert size.charge == pytest.approx(-0.25)
    assert_extents(size, [100.25, 100.25, 100.25], 1.5)


@pytest.mark.parametrize(
    "line",
    [
        "ATOM 100001 CA ALA A 10001 -1234.567 1000.000 2.000 0.1000 1.8700",
        "ATOM 100001 CA ALA 10001 -1234.567 1000.000 2.000 0.1000 1.8700",
        "HETATM 100001 CA ALA AB 10001 -1234.567 1000.000 2.000 0.1 1.87",
    ],
)
def test_free_format_beyond_fixed_column_limits(line):
    """Whitespace-delimited records are not limited by PDB field widths."""
    size = parse(line)
    assert size.gotatom + size.gothet == 1
    assert size.charge == pytest.approx(0.1)
    assert_extents(size, [-1234.567, 1000.0, 2.0], 1.87)


@pytest.mark.parametrize(
    "x, y, z",
    [
        (-22.340, 15.180, -188.097),
        (15.180, 1188.097, 2.104),
        (-999.999, -999.999, -999.999),
        (9999.999, 9999.999, 9999.999),
    ],
)
def test_fixed_columns_without_separators(x, y, z):
    """Fixed-column coordinates are read by column when they run together."""
    line = fixed_pqr_line(x, y, z)
    assert len(line.split()) < 11
    size = parse(line)
    assert size.charge == pytest.approx(-0.25)
    assert_extents(size, [x, y, z], 1.5)


def test_whitespace_option_output():
    """Records written with ``--whitespace`` are parsed by whitespace."""
    line = "HETATM10570  O    HOH   326     -21.527   36.762  -17.369 -0.8340 1.6612"
    size = parse(line)
    assert size.gothet == 1
    assert size.charge == pytest.approx(-0.834)
    assert_extents(size, [-21.527, 36.762, -17.369], 1.6612)


def test_pdb_occupancy_and_temperature_factor_without_separator():
    """PDB occupancy and temperature factor are read by column if needed."""
    line = (
        "ATOM      7  SD  MET A   1     -27.076  41.327 -18.590"
        "  1.00101.76           S"
    )
    size = parse(line)
    assert size.charge == pytest.approx(1.0)
    assert_extents(size, [-27.076, 41.327, -18.590], 101.76)


def test_non_atom_records_are_ignored():
    """Only ATOM and HETATM records contribute to the dimensions."""
    size = parse(
        "REMARK   1 PQR file generated by PDB2PQR 1.0 2.0 3.0 4.0 5.0",
        "CRYST1   40.000   50.000   60.000  90.00  90.00  90.00 P 1",
        fixed_pqr_line(1.0, 2.0, 3.0),
        "TER",
        "END",
    )
    assert size.gotatom == 1
    assert_extents(size, [1.0, 2.0, 3.0], 1.5)


@pytest.mark.parametrize(
    "line",
    [
        "ATOM      1  N   GLY A   1",
        "ATOM 1 N GLY A 1 1.0 2.0 3.0 -0.25 N",
    ],
)
def test_unparseable_atom_record(line):
    """An atom record that cannot be parsed is an error, not skipped."""
    with pytest.raises(ValueError, match="Unable to parse atom record"):
        parse(line)
